from django.contrib import admin
from celere_app.models import *

admin.site.register(SerieEscolar)
admin.site.register(NivelEnsino)
admin.site.register(Turma)
admin.site.register(Aluno)
admin.site.register(Bilhete)
admin.site.register(Responsavel)
admin.site.register(Comunicado)
admin.site.register(Planejamento)
admin.site.register(Profissional)
admin.site.register(Gestor)
admin.site.register(Professor)
admin.site.register(Leciona)
admin.site.register(Disc_Turma)
admin.site.register(Disciplina)
admin.site.register(Nota)
admin.site.register(Frequencia)
admin.site.register(ChecklistItem)