# Generated by Django 4.2.7 on 2023-12-08 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('registration_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateTimeField(verbose_name='Data de nascimento')),
            ],
            options={
                'db_table': 'Aluno',
            },
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_level', models.CharField(choices=[('ens_infantil', 'Ensino Infantil'), ('ens_fundamental1', 'Ensino Fundamental I'), ('ens_fundamental2', 'Ensino Fundamental II'), ('ens_medio', 'Ensino Médio'), ('ens_medio_tec', 'Ensino Médio Técnico'), ('eja', 'EJA')], max_length=50)),
            ],
            options={
                'db_table': 'NivelEnsino',
            },
        ),
        migrations.CreateModel(
            name='SerieEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_grade', models.CharField(choices=[('bercario', 'Berçário'), ('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('g4', 'G4'), ('g5', 'G5'), ('1ano', '1º ano'), ('2ano', '2º ano'), ('3ano', '3º ano'), ('4ano', '4º ano')], max_length=100)),
            ],
            options={
                'db_table': 'SerieEscolar',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('school_grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_serie', to='celere_app.serieescolar')),
                ('school_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas_nivel', to='celere_app.nivelensino')),
            ],
            options={
                'db_table': 'Turma',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('kinship', models.CharField(max_length=15)),
                ('reg_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis_aluno', to='celere_app.aluno')),
            ],
            options={
                'db_table': 'Responsavel',
            },
        ),
        migrations.CreateModel(
            name='Bilhete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('reg_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes_aluno', to='celere_app.aluno')),
            ],
            options={
                'db_table': 'Bilhete',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='id_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celere_app.turma'),
        ),
    ]
