# Generated by Django 4.2.7 on 2023-12-14 01:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('celere_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da disciplina')),
            ],
            options={
                'db_table': 'Disciplina',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=150, verbose_name='E-mail')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefone')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
            ],
            options={
                'db_table': 'Profissional',
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do aluno'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='registration_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número de matrícula'),
        ),
        migrations.AlterField(
            model_name='nivelensino',
            name='school_level',
            field=models.CharField(choices=[('ens_infantil', 'Ensino Infantil'), ('ens_fundamental1', 'Ensino Fundamental I'), ('ens_fundamental2', 'Ensino Fundamental II'), ('ens_medio', 'Ensino Médio'), ('ens_medio_tec', 'Ensino Médio Técnico'), ('eja', 'EJA')], max_length=50, verbose_name='Nível de ensino'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='kinship',
            field=models.CharField(max_length=15, verbose_name='Parentesco'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome do responsável'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='tel',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='serieescolar',
            name='school_grade',
            field=models.CharField(choices=[('bercario', 'Berçário'), ('g1', 'G1'), ('g2', 'G2'), ('g3', 'G3'), ('g4', 'G4'), ('g5', 'G5'), ('1ano', '1º ano'), ('2ano', '2º ano'), ('3ano', '3º ano'), ('4ano', '4º ano')], max_length=100, verbose_name='Série escolar'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome da turma'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('id_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_profissional', to='celere_app.profissional')),
            ],
            options={
                'db_table': 'Professor',
            },
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('end_date', models.DateTimeField(verbose_name='Data de término')),
                ('tags', models.CharField(choices=[('Urg', 'Urgente'), ('Imp', 'Importante'), ('Norm', 'Normal'), ('Baixa', 'Baixa prioridade')], max_length=20, verbose_name='Tags')),
                ('checklist', models.ManyToManyField(blank=True, to='celere_app.checklistitem')),
                ('id_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos_profissional', to='celere_app.profissional')),
            ],
            options={
                'db_table': 'Planejamento',
            },
        ),
        migrations.CreateModel(
            name='Leciona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leciona_disciplina', to='celere_app.disciplina')),
                ('cpf_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leciona_professor', to='celere_app.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('id_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestor_profissional', to='celere_app.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('frequency', models.CharField(choices=[('P', 'Presente'), ('NP', 'Não Presente')], max_length=2, verbose_name='Frequência')),
                ('disciplina_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias_disciplina', to='celere_app.disciplina')),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias_aluno', to='celere_app.aluno')),
            ],
            options={
                'db_table': 'Frequencia',
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('text', models.CharField(max_length=500, verbose_name='Texto')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('end_date', models.DateTimeField(verbose_name='Data de término')),
                ('tags', models.CharField(choices=[('Urg', 'Urgente'), ('Imp', 'Importante'), ('Norm', 'Normal'), ('Baixa', 'Baixa prioridade')], max_length=20, verbose_name='Tags')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_comunicado', to='celere_app.profissional')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leitor_comunicado', to='celere_app.profissional')),
            ],
            options={
                'db_table': 'Comunicado',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tl', '1ª Avaliação'), ('T2', '2ª Avaliação'), ('T3', '3º Avaliação'), ('T4', 'Final')], max_length=2, verbose_name='Categoria')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('grade', models.FloatField(default=0, verbose_name='Nota')),
                ('year', models.IntegerField()),
                ('aluno_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_aluno', to='celere_app.aluno')),
                ('disciplina_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_disciplina', to='celere_app.disciplina')),
            ],
            options={
                'db_table': 'Nota',
                'unique_together': {('category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Disc_Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_turma_disciplina', to='celere_app.disciplina')),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disc_turma_turma', to='celere_app.turma')),
            ],
            options={
                'db_table': 'Disc_Turma',
                'unique_together': {('code_disciplina', 'id_turma')},
            },
        ),
    ]
