# Generated by Django 4.2.7 on 2023-12-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celere_app', '0002_checklistitem_disciplina_profissional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='reader',
        ),
        migrations.AddField(
            model_name='comunicado',
            name='reader',
            field=models.ManyToManyField(related_name='leitores_comunicado', to='celere_app.profissional'),
        ),
    ]
