# Generated by Django 4.2.7 on 2024-02-17 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celere_app', '0003_remove_comunicado_reader_comunicado_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilhete',
            name='reg_prof',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes_prof', to='celere_app.profissional'),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Texto'),
        ),
    ]
