# Generated by Django 4.2.7 on 2024-02-17 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('celere_app', '0004_bilhete_reg_prof_alter_bilhete_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='reg_prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilhetes_prof', to='celere_app.profissional'),
        ),
    ]
