# Generated by Django 4.2.7 on 2024-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celere_app', '0005_alter_bilhete_reg_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Texto'),
        ),
    ]
