# Generated by Django 4.2.7 on 2024-02-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celere_app', '0006_alter_comunicado_text'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='checklistitem',
            table='ChecklistItem',
        ),
    ]
